insert into product (name, summary, description, price, fk_category_id) values ('Motorola ZN200', 'Linux / Java-based MOTOMAGX', 'A beachy and coastal vibe with nautical accents', 1781.65, 3);
insert into product (name, summary, description, price, fk_category_id) values ('Sony Ericsson Z520', 'Feature phone', 'A modern and sleek design with plenty of natural light', 2501.47, 15);
insert into product (name, summary, description, price, fk_category_id) values ('Motorola W395', 'Feature phone', 'A minimalist and clean aesthetic with pops of color', 4952.0, 9);
insert into product (name, summary, description, price, fk_category_id) values ('Lenovo Yoga Tablet 10', 'Android 4.2', 'A cozy and inviting space perfect for relaxation', 4337.35, 13);
insert into product (name, summary, description, price, fk_category_id) values ('Plum Ram 8', 'Feature phone', 'An eclectic mix of vintage and contemporary decor', 4220.17, 7);
insert into product (name, summary, description, price, fk_category_id) values ('Tecno Pop 1s', 'Android 8.1 Oreo', 'A rustic and charming atmosphere with a fireplace', 4610.44, 5);
insert into product (name, summary, description, price, fk_category_id) values ('Intex Aqua Speed', 'Android 4.4.2, up to 5.0', 'A rustic and charming atmosphere with a fireplace', 1874.15, 4);
insert into product (name, summary, description, price, fk_category_id) values ('TCL 20 SE', 'Android 11, TCL UI', 'A glamorous and luxurious setting with crystal chandeliers', 2865.52, 5);
insert into product (name, summary, description, price, fk_category_id) values ('Asus Zenfone 3 Deluxe ZS570KL', 'Android 6.1, up to Android 8, ZenUI 3', 'A rustic and charming atmosphere with a fireplace', 4501.81, 16);
insert into product (name, summary, description, price, fk_category_id) values ('i-mate K-JAM', 'Microsoft Windows Mobile 5.0 PocketPC', 'A beachy and coastal vibe with nautical accents', 3867.62, 2);
insert into product (name, summary, description, price, fk_category_id) values ('Samsung Galaxy A Quantum', 'Android 10, One UI 2', 'A modern and sleek design with plenty of natural light', 4362.18, 9);
insert into product (name, summary, description, price, fk_category_id) values ('verykool Sl5200 Eclipse', 'Android 6.0', 'An eclectic mix of vintage and contemporary decor', 2641.41, 5);
insert into product (name, summary, description, price, fk_category_id) values ('Samsung Galaxy Gear', 'Tizen OS', 'A minimalist and clean aesthetic with pops of color', 1653.3, 19);
insert into product (name, summary, description, price, fk_category_id) values ('Micromax A110Q Canvas 2 Plus', 'Android 4.2', 'A cozy and inviting space perfect for relaxation', 4247.21, 4);
insert into product (name, summary, description, price, fk_category_id) values ('vivo Y30 Standard', 'Android 10, Funtouch 10.5', 'A glamorous and luxurious setting with crystal chandeliers', 3150.37, 7);
insert into product (name, summary, description, price, fk_category_id) values ('Samsung E210', 'Feature phone', 'An eclectic mix of vintage and contemporary decor', 2421.78, 14);
insert into product (name, summary, description, price, fk_category_id) values ('Amoi E850', 'Microsoft Windows Mobile 5.0 for &hellip;', 'A modern and sleek design with plenty of natural light', 2750.23, 4);
insert into product (name, summary, description, price, fk_category_id) values ('Celkon C5', 'Feature phone', 'A beachy and coastal vibe with nautical accents', 2157.81, 5);
insert into product (name, summary, description, price, fk_category_id) values ('Nokia 6600 fold', 'Feature phone', 'A zen and peaceful retreat with a meditation corner', 2642.13, 17);
insert into product (name, summary, description, price, fk_category_id) values ('Motorola Moto E4 (USA)', 'Android 7.1', 'A minimalist and clean aesthetic with pops of color', 1890.41, 15);
